version: "3.8"
services:
  library:
    image: library-image:latest
    build:
      context: .
    container_name: library
    ports:
      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5431/library-db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - library-network

  library-db:
    image: postgres:latest
    container_name: library-db
    environment:
      POSTGRES_DB: library-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    networks:
      - library-network

networks:
  library-network: