spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: bakulibrary
    hikari:
      max-lifetime: 20000
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
#  main:
#    web-application-type: none